imports:
    - { resource: config.yml }
monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        output:
            type: stream
            path: php://stdout
            level: debug
            channels: ['!php', '!event', '!doctrine', '!request', '!security', '!crawler_channel']

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }
