# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        mvc:
            pattern: ^/mvc
            stateless: true
            anonymous: true
        main:
            pattern: ^/
            anonymous:    true

    access_control:
        - { path: ^/mvc,  role: IS_AUTHENTICATED_ANONYMOUSLY}
