<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_connection' shared service.

return $this->services['doctrine_mongodb.odm.default_connection'] = new \Doctrine\MongoDB\Connection('mongodb://'.$this->getEnv('string:DB_HOST').':27017', ['db' => $this->getEnv('DB_NAME')], ${($_ = isset($this->services['doctrine_mongodb.odm.default_configuration']) ? $this->services['doctrine_mongodb.odm.default_configuration'] : $this->load('getDoctrineMongodb_Odm_DefaultConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_mongodb.odm.event_manager']) ? $this->services['doctrine_mongodb.odm.event_manager'] : $this->load('getDoctrineMongodb_Odm_EventManagerService.php')) && false ?: '_'}, []);
