<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Infrastructure\Doctrine\DoctrineEventPublisher' shared autowired service.

$a = ${($_ = isset($this->services['doctrine_mongodb.odm.default_document_manager']) ? $this->services['doctrine_mongodb.odm.default_document_manager'] : $this->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService.php')) && false ?: '_'};

return $this->services['Mvc\\Infrastructure\\Doctrine\\DoctrineEventPublisher'] = new \Mvc\Infrastructure\Doctrine\DoctrineEventPublisher($a, $a, ${($_ = isset($this->services['Mvc\\Infrastructure\\CQRS\\Event\\JSONEventSerializer']) ? $this->services['Mvc\\Infrastructure\\CQRS\\Event\\JSONEventSerializer'] : $this->load('getJSONEventSerializerService.php')) && false ?: '_'});
