<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_mongodb.odm.default_document_manager' shared service.

$this->services['doctrine_mongodb.odm.default_document_manager'] = $instance = \Doctrine\ODM\MongoDB\DocumentManager::create(${($_ = isset($this->services['doctrine_mongodb.odm.default_connection']) ? $this->services['doctrine_mongodb.odm.default_connection'] : $this->load('getDoctrineMongodb_Odm_DefaultConnectionService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_mongodb.odm.default_configuration']) ? $this->services['doctrine_mongodb.odm.default_configuration'] : $this->load('getDoctrineMongodb_Odm_DefaultConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['doctrine_mongodb.odm.event_manager']) ? $this->services['doctrine_mongodb.odm.event_manager'] : $this->load('getDoctrineMongodb_Odm_EventManagerService.php')) && false ?: '_'});

${($_ = isset($this->services['doctrine_mongodb.odm.default_manager_configurator']) ? $this->services['doctrine_mongodb.odm.default_manager_configurator'] : ($this->services['doctrine_mongodb.odm.default_manager_configurator'] = new \Doctrine\Bundle\MongoDBBundle\ManagerConfigurator([]))) && false ?: '_'}->configure($instance);

return $instance;
