<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.Mvc\UserInterface\Http\Validator\EmptyValidator' shared autowired service.

return $this->services['autowired.Mvc\\UserInterface\\Http\\Validator\\EmptyValidator'] = new \Mvc\UserInterface\Http\Validator\EmptyValidator();
