<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserDiseaseCreatorService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserDiseaseCreatorService'] = new \Mvc\Application\Service\HistoryUserDiseaseCreatorService(${($_ = isset($this->services['Mvc\\Domain\\UserRepository']) ? $this->services['Mvc\\Domain\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\HistoryUserDiseaseRepository']) ? $this->services['Mvc\\Domain\\HistoryUserDiseaseRepository'] : $this->load('getHistoryUserDiseaseRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\DiseaseRepository']) ? $this->services['Mvc\\Domain\\DiseaseRepository'] : $this->load('getDiseaseRepositoryService.php')) && false ?: '_'});
