<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserVaccineFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserVaccineFindersService'] = new \Mvc\Application\Service\HistoryUserVaccineFindersService(${($_ = isset($this->services['Mvc\\Domain\\HistoryUserVaccineRepository']) ? $this->services['Mvc\\Domain\\HistoryUserVaccineRepository'] : $this->load('getHistoryUserVaccineRepositoryService.php')) && false ?: '_'});
