<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserDonationsPatientFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserDonationsPatientFindersService'] = new \Mvc\Application\Service\HistoryUserDonationsPatientFindersService(${($_ = isset($this->services['Mvc\\Domain\\UserRepository']) ? $this->services['Mvc\\Domain\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\HistoryUserDonationsRepository']) ? $this->services['Mvc\\Domain\\HistoryUserDonationsRepository'] : $this->load('getHistoryUserDonationsRepositoryService.php')) && false ?: '_'});
