<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserOperationsFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserOperationsFindersService'] = new \Mvc\Application\Service\HistoryUserOperationsFindersService(${($_ = isset($this->services['Mvc\\Domain\\HistoryUserOperationsRepository']) ? $this->services['Mvc\\Domain\\HistoryUserOperationsRepository'] : $this->load('getHistoryUserOperationsRepositoryService.php')) && false ?: '_'});
