<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserDiseasePatientFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserDiseasePatientFindersService'] = new \Mvc\Application\Service\HistoryUserDiseasePatientFindersService(${($_ = isset($this->services['Mvc\\Domain\\UserRepository']) ? $this->services['Mvc\\Domain\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\HistoryUserDiseaseRepository']) ? $this->services['Mvc\\Domain\\HistoryUserDiseaseRepository'] : $this->load('getHistoryUserDiseaseRepositoryService.php')) && false ?: '_'});
