<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HelloWorldService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HelloWorldService'] = new \Mvc\Application\Service\HelloWorldService();
