<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\HistoryUserDonationsFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\HistoryUserDonationsFindersService'] = new \Mvc\Application\Service\HistoryUserDonationsFindersService(${($_ = isset($this->services['Mvc\\Domain\\HistoryUserDonationsRepository']) ? $this->services['Mvc\\Domain\\HistoryUserDonationsRepository'] : $this->load('getHistoryUserDonationsRepositoryService.php')) && false ?: '_'});
