<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Contracts\HttpClient\HttpClientInterface' shared autowired service.

return $this->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] = new \Symfony\Component\HttpClient\CurlHttpClient();
