<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\UserInterface\Http\Middleware\HttpExceptionMiddleware' shared autowired service.

return $this->services['Mvc\\UserInterface\\Http\\Middleware\\HttpExceptionMiddleware'] = new \Mvc\UserInterface\Http\Middleware\HttpExceptionMiddleware(false);
