<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Infrastructure\CQRS\Event\JSONEventSerializer' shared autowired service.

return $this->services['Mvc\\Infrastructure\\CQRS\\Event\\JSONEventSerializer'] = new \Mvc\Infrastructure\CQRS\Event\JSONEventSerializer(new RewindableGenerator(function () {
    return new \EmptyIterator();
}, 0));
