<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_serializer.object_constructor' shared service.

return $this->services['jms_serializer.object_constructor'] = new \JMS\Serializer\Construction\UnserializeObjectConstructor();
