<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mail_service' shared autowired service.

return $this->services['mail_service'] = new \AppBundle\Mvc\Notifier\MailService(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load('getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, $this->getEnv('MAILER_FROM'), true, 'srosch@uoc.edu');
