<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Component\HttpClient\NativeHttpClient' shared autowired service.

return $this->services['Symfony\\Component\\HttpClient\\NativeHttpClient'] = new \Symfony\Component\HttpClient\NativeHttpClient();
