<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\OnlineConsultationPendingFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\OnlineConsultationPendingFindersService'] = new \Mvc\Application\Service\OnlineConsultationPendingFindersService(${($_ = isset($this->services['Mvc\\Domain\\UserRepository']) ? $this->services['Mvc\\Domain\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\OnlineConsultationRepository']) ? $this->services['Mvc\\Domain\\OnlineConsultationRepository'] : $this->load('getOnlineConsultationRepositoryService.php')) && false ?: '_'});
