<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'swiftmailer.mailer.default.transport.dynamic' shared service.

return $this->services['swiftmailer.mailer.default.transport.dynamic'] = \Symfony\Bundle\SwiftmailerBundle\DependencyInjection\SwiftmailerTransportFactory::createTransport(['transport' => $this->getEnv('MAILER_TRANSPORT'), 'url' => NULL, 'username' => NULL, 'password' => NULL, 'host' => $this->getEnv('MAILER_HOST'), 'port' => $this->getEnv('MAILER_PORT'), 'timeout' => 30, 'source_ip' => NULL, 'local_domain' => NULL, 'encryption' => NULL, 'auth_mode' => NULL, 'command' => '/usr/sbin/sendmail -bs'], ${($_ = isset($this->services['router.request_context']) ? $this->services['router.request_context'] : $this->getRouter_RequestContextService()) && false ?: '_'}, new \Swift_Events_SimpleEventDispatcher());
