<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Domain\Factory\TokenFactory' shared autowired service.

return $this->services['Mvc\\Domain\\Factory\\TokenFactory'] = new \Mvc\Domain\Factory\SimpleTokenFactory('secret123456S*', 14);
