<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\UserDocumentFindersService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\UserDocumentFindersService'] = new \Mvc\Application\Service\UserDocumentFindersService(${($_ = isset($this->services['Mvc\\Domain\\UserDocumentRepository']) ? $this->services['Mvc\\Domain\\UserDocumentRepository'] : $this->load('getUserDocumentRepositoryService.php')) && false ?: '_'});
