<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Mvc\Application\General\UuidGenerator' shared autowired service.

return $this->services['AppBundle\\Mvc\\Application\\General\\UuidGenerator'] = new \AppBundle\Mvc\Application\General\UuidGenerator();
