<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Mvc\Application\Service\UserDocumentCreatorService' shared autowired service.

return $this->services['Mvc\\Application\\Service\\UserDocumentCreatorService'] = new \Mvc\Application\Service\UserDocumentCreatorService(${($_ = isset($this->services['Mvc\\Domain\\UserRepository']) ? $this->services['Mvc\\Domain\\UserRepository'] : $this->load('getUserRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Domain\\UserDocumentRepository']) ? $this->services['Mvc\\Domain\\UserDocumentRepository'] : $this->load('getUserDocumentRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Mvc\\Notifier\\UserMailSenderInterface']) ? $this->services['Mvc\\Notifier\\UserMailSenderInterface'] : $this->load('getUserMailSenderInterfaceService.php')) && false ?: '_'});
