<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MvcDomainUserPrimaryCenterHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @ReferenceOne */
        if (isset($data['doctor'])) {
            $reference = $data['doctor'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['doctor'], $reference);
            $mongoId = ClassMetadata::getReferenceId($reference, $this->class->fieldMappings['doctor']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['doctor']->setValue($document, $return);
            $hydratedData['doctor'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['nurse'])) {
            $reference = $data['nurse'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['nurse'], $reference);
            $mongoId = ClassMetadata::getReferenceId($reference, $this->class->fieldMappings['nurse']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['nurse']->setValue($document, $return);
            $hydratedData['nurse'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['center'])) {
            $reference = $data['center'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['center'], $reference);
            $mongoId = ClassMetadata::getReferenceId($reference, $this->class->fieldMappings['center']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['center']->setValue($document, $return);
            $hydratedData['center'] = $return;
        }
        return $hydratedData;
    }
}