<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBhzbtk2\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBhzbtk2/appDevProjectContainer.php') {
    touch(__DIR__.'/ContainerBhzbtk2.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\ContainerBhzbtk2\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \ContainerBhzbtk2\appDevProjectContainer([
    'container.build_hash' => 'Bhzbtk2',
    'container.build_id' => '63bd391d',
    'container.build_time' => 1654422291,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBhzbtk2');
